// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV0vgDUMOdJhi7DfrDKH49djcniOU2GHQ',
    appId: '1:83153149289:web:164ce14dae78d5b6c8b1f8',
    messagingSenderId: '83153149289',
    projectId: 'usainua-b3321',
    authDomain: 'usainua-b3321.firebaseapp.com',
    storageBucket: 'usainua-b3321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJmy8D6dz2tEoBmN7sO2SfDaFyQfrLKQc',
    appId: '1:83153149289:android:7de07729f8990130c8b1f8',
    messagingSenderId: '83153149289',
    projectId: 'usainua-b3321',
    storageBucket: 'usainua-b3321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaIcj0lun2ayS3USZxTEFrc3QF4mQHpBU',
    appId: '1:83153149289:ios:70ab1090b89764f2c8b1f8',
    messagingSenderId: '83153149289',
    projectId: 'usainua-b3321',
    storageBucket: 'usainua-b3321.appspot.com',
    androidClientId: '83153149289-ccg1mkgous0mmqh29vj3ohfebrnae5g8.apps.googleusercontent.com',
    iosClientId: '83153149289-5ta0bc64f34kb83teiibkfa5m0hqi6ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.usainua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaIcj0lun2ayS3USZxTEFrc3QF4mQHpBU',
    appId: '1:83153149289:ios:70ab1090b89764f2c8b1f8',
    messagingSenderId: '83153149289',
    projectId: 'usainua-b3321',
    storageBucket: 'usainua-b3321.appspot.com',
    androidClientId: '83153149289-ccg1mkgous0mmqh29vj3ohfebrnae5g8.apps.googleusercontent.com',
    iosClientId: '83153149289-5ta0bc64f34kb83teiibkfa5m0hqi6ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.usainua',
  );
}
