class AppIcons {
  AppIcons._();
  static const String yey = 'assets/icons/yey.svg';
  static const String lock = 'assets/icons/Lock.svg';
  static const String profile = 'assets/icons/Profile.svg';
  static const String profilePlus = 'assets/icons/addUser.svg';
  static const String password = 'assets/icons/Password.svg';
  static const String pageViewIndicator = 'assets/icons/pageViewIndicator.svg';
  static const String arrowLeft = 'assets/icons/arrowLeft.svg';
  static const String arrowRight = 'assets/icons/arrowRight.svg';
  static const String greenCheck = 'assets/icons/greenCheck.svg';
  static const String snake = 'assets/icons/snake.svg';
  static const String snakePng = 'assets/icons/snakePng.png';
  static const String buy = 'assets/icons/Buy.svg';
  static const String moneyBag = 'assets/icons/money-bag.svg';
  static const String location = 'assets/icons/location.svg';
  static const String copy = 'assets/icons/copy.svg';
  static const String copyLocation = 'assets/icons/copyLocation.svg';
  static const String edit = 'assets/icons/Edit.svg';
  static const String carbonDioxide1 = 'assets/icons/carbon-dioxide1.svg';
  static const String carbonDioxide2 = 'assets/icons/carbon-dioxide2.svg';
  static const String notification = 'assets/icons/Notification.svg';
  static const String massage = 'assets/icons/massage.svg';
  static const String calculator = 'assets/icons/calculator.svg';
  static const String plus = 'assets/icons/plus.svg';
  static const String profileBold = 'assets/icons/Profilebold.svg';
  static const String home = 'assets/icons/Home.svg';
  static const String homeBold = 'assets/icons/Homecurrent.svg';
  static const String choice = 'assets/icons/Bag.svg';
  static const String choiceBold = 'assets/icons/Bagbold.svg';
  static const String box = 'assets/icons/box.svg';
  static const String boxBold = 'assets/icons/box.svg';
  // static const String emptyfoto = 'assets/icons/emptyfoto.svg';
  // static const String arrowDownCircle = 'assets/icons/arrowDownCircle.svg';
  // static const String arrowLeftCircle = 'assets/icons/arrowLeftCircle.svg';
  // static const String plusPlus = 'assets/icons/plusPlus.svg';
}
